name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your target branch
  pull_request:
    branches:
      - main  # Change this to your target branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for assuming the IAM role
      contents: read    # Required for checking out the code

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest  # Specify your Terraform version
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: eu-central-1

      - name: Terraform Init
        run: |
          pwd
          cd terraform/envs/dev
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
         cd terraform/envs/dev
         terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: |
      #     cd terraform/envs/dev
      #     terraform apply -auto-approve tfplan
      #   if: github.ref == 'refs/heads/main'  # Apply only on main branch

      - name: Clean up
        run: rm -f tfplan
